### PR TITLE
Split into full and base packages

### PR DESCRIPTION
**Pull request by mattwthompson**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mattwthompson** [comment]
@conda-forge-admin please rerender

**Comment by peastman** [comment]
Seems like a reasonable approach.  The only difference between `openmmforcefields` and `openmmforcefields-base` is that the latter does not list `openff-toolkit` and `openff-forcefields` as dependencies?

**Comment by mattwthompson** [comment]
> Seems like a reasonable approach. The only difference between `openmmforcefields` and `openmmforcefields-base` is that the latter does not list `openff-toolkit` and `openff-forcefields` as dependencies?

Yes, exactly.

**Comment by mattwthompson** [comment]
Windows builds are failing since we don't build the OpenFF stack for Windows. Is it important that this package is built on Windows? I don't think a user could install this package (as in literally **this** package via conda, not necessarily other builds of `openmmforcefields`) since it would have no way of pulling down the OpenFF packages.

**Comment by jchodera** [comment]
@mattwthompson Thanks for highlighting this issue!

As I understand it, the dependency chain is
```
[openff toolkit examples] -> [openmmforcefields] -> [openff toolkit]
```
Why is the best solution to split `openmmforcefields` into two packages, rather than just split off the OpenFF toolkit examples (some of which are quite elaborate and use many external tools) into a separate repo/package?

**Comment by mattwthompson** [comment]
Just to clear things up a little, the tension is only in testing and development environments. When examples are run in [CI](https://github.com/openforcefield/openff-toolkit/blob/dae71c874e065c11cf5d9556391aec5de3113e17/.github/workflows/examples.yml#L98-L103), we have to remove the release build of the toolkit that was pulled in while installing `openmmforcefields`. The same thing happens locally; whenever I run `conda install openmmforcefields` in an development environment I have to remember to re-install my local development build just as in the linked CI script.

> rather than just split off the OpenFF toolkit examples (some of which are quite elaborate and use many external tools) into a separate repo/package?

Agree completely and this is [exactly what's done](https://github.com/openforcefield/openff-toolkit/blob/dae71c874e065c11cf5d9556391aec5de3113e17/.github/workflows/examples.yml#L98-L103) on the packaging side of things. (Credit to Josh and Jeff, I didn't have any part in this one.) In principle these could use `openmmforcefields-base` but there's not much reason to do so since there is not a problem here - it's intentionally pulling down a packaged version of the toolkit.

**Comment by mikemhenry** [comment]
@mattwthompson do you still need/want this?

**Comment by mattwthompson** [comment]
We don't need it, but you want this change in I will gladly rebase.

If you all think it's not worth the complexity or for any other reason you would prefer keeping the current structure, this can be closed.

**Comment by mattwthompson** [comment]
@conda-forge-admin please rerender

**Comment by mattwthompson** [comment]
I no longer need this for the original purpose, but this strategy might be useful for supporting platforms that the AmberTools package currently has issues with.

**Comment by mikemhenry** [comment]
Good call, why do we need `recipe/build_base.sh`?

**Comment by mattwthompson** [comment]
I don't totally recall why ... the best explanation I can offer is that it's how we do it on our [feedstocks](https://github.com/conda-forge/openff-interchange-feedstock/blob/caddd745dd19ddb3769c1ba009cacd23516eab34/recipe/meta.yaml). I recall something wart-y when first making those splits but now it looks like it [might be doable](https://github.com/conda-forge/conda-forge.github.io/issues/746) without using the shell scripts

**Comment by mattwthompson** [comment]
@conda-forge-admin, please rerender

**Comment by mattwthompson** [comment]
It'd take a bit of digging to figure out if/why this can be built without a script. I'm not eager to do that

**Comment by mattwthompson** [comment]
@conda-forge-admin please rerender

**Comment by mikemhenry** [comment]
I'm worried that most users will want to be able to use ambertools splitting it out might cause confusion, but I supposed they would have to know to install the `-base` version to work around it so it shouldn't come as a surprise.

**Comment by mattwthompson** [comment]
Yeah, I view the "base" package as opt-in and something you'd not accidentally use, but it can be useful for powerusers or some development tooling.

For example, I don't think it would be a good idea to recommend it in user-facing docs unless there's a strong need for it

**Comment by mikemhenry** [comment]
I think they may be an issue with `0.12.0` in some cases, so I would like to wait on splitting out the package into a base package until the dust settles on that, and either do this on `0.12.1` or on `0.12.0` once we confirm there are not any issues.

**Comment by mikemhenry** [comment]
@conda-forge-admin, please rerender

**Comment by mattwthompson** [comment]
Converting back into draft until a time if/when we decide we want this, but will keep up to date

**Comment by mattwthompson** [comment]
This has oscillated back to being undesired, but can oscillate back to revived if wished

**Pull request closed without merging**
